---

- name: create database
  community.mysql.mysql_db:
    login_user: root
    name: "{{ apache_db_name }}"
    state: present

- name: create db user
  community.mysql.mysql_user:
    name: "{{ apache_db_user }}"
    password: "{{ apache_db_password }}"
    update_password: on_create
    priv: "{{ apache_db_name }}.*:ALL"
    state: present
